### ISSUE TITLE
https://github.com/ao-libre/ao-java

### ISSUE THREAD

**Issue by RecoX** [gorlok/aoj-server#2]
esto te puede interesar: https://github.com/ao-libre/ao-java

cualquier cosa contactanos al discord: http://www.argentumonline.org

**Comment by gorlok** [comment]
Aun no pude revisar el proyecto, pero me parece que es muy interesante lo que están haciendo. También había pensado en implementar un cliente usando libGDX. Tengo entendido que están haciendo una implementación inspirada en AO, desde cero y muy diferente, desde la mecánica, protocolo, estructuras, etc. No estoy seguro si podrá ser compatible con este servidor, pero igual debería revisarlo.
